@startuml
class Folder {
 createdAt: int
 updatedAt: int
 folder: Folder
 mdFile: MDFile
 method1()
 method2()
}

class MDFile {
  id: int
  createdAt: int
  updatedAt: int
  content: string
}

MDFile }-- Folder
Folder }-- Folder

@enduml

